### PR TITLE
Idoychev/websocket integration

### LINKED ISSUE #9: Add button to randomize the playing field
The shell offers a button to randomize the playing field (with a confirmation dialog to make sure you don't press it on accident). We should also have this in the web frontend. It works by sending a `RandomizeField` message with no arguments to the refbox, although I don't know whether the websocket backend already supports that.

### LINKED ISSUE #10: Attention messages should be more visible
The attention messages usually contain important things that should immediately catch the viewer's attention (hence the name). Currently, they only show up in the log and are rather easy to miss. They should be displayed more visibly, e.g.,
* With a popup, similar to the order confirmation dialog
* In a separate div, e.g., above or below the log

### LINKED ISSUE #12: Remove teamname from robot name
With the new UI it is already very clear which team a robot belongs to. Removing the team name saves space and does not make the displayed information less clear to understand.

### LINKED ISSUE #13: Move the robot name for better readability
The positioning of the robot name (centered, one line above the information) creates a cluttered look. I'd suggest either moving the robot name on the same line (as the first item), or have it left-aligned. If you keep it left aligned it could be helpful to add horizontal lines between the entry for each robot.

### LINKED ISSUE #14: Add option to set websocket port throught the UI/through a config file
The port of the websocket backend is configurable through the config file of the refbox, in case the arbitrary default port of 1234 is already used by other applications. It should be possible to change the port the frontend is connecting to in an accessible way.

### LINKED ISSUE #16: Add indicator for lost connection
Currently the frontend doesn't indicate if the client lost connection to the backend. The standard JavaScript implementation of WebSockets provides something like the following that is called when the connection breaks down:
`
connection.onclose = function(e) {
  //do stuff
};
`
It would be nice if there was some indication, for that to make it easier for users to spot a dead connection.

### PR DESCRIPTION
**Pull request by userin4o**
This PR fixes #14, fixes #13, fixes #12, fixes #9, fixes #10 
It includes total replacement of the Rest API dependencies with the Refbox Websocket:
  - Subscribing to Refbox Websocket  
  - Implementations of commands for: 
    - Setting Teamname, State, Phase (with a dropdown to choose specific Phase)
    - Pause/Play/Next and Previous phase buttons
    - Randomizing Field
    - Changing Websocket Port
    - Confirmation box to confirm delivery 
    - Set robots to maintenance
  - Displaying gamestate, robot, order, cyan machine and points information coming from the Websocket connection. 
  - General visual improvements to UI

### CODE REVIEW

**Comment by snoato** [comment]
Great work integrating the new backend and incorporating the suggestions/issues! Thank you for the work you put into this! 

Minor suggestions/issues: 
- Regarding the issues #9 and #14 I'm not sure if the icons you chose work that well, I had trouble figuring out what they are supposed to mean, however this should be tested within the team/with members of other teams. 
- Regarding issue #10  the attention messages should still be integrated into the log (as with the refbox shell, this way they are still readable if the user missed the "pop-up"). Additionally I would suggest switching to a strict vertical layout (not two messages side-by side), even if only one message is shown in that case.

**Comment by userin4o** [comment]
Thanks for the feedback!

**Comment by userin4o** [comment]
Thanks for the feedback!
- I think after the first use it is easy to understand why they are there for. There is also a tooltip to describe what they do
- I will make sure to display them in the log as well and also change the layout (it was vertical at first, let me know if that is nicer)

**Comment by snoato** [comment]
Thanks for the additional changes! I think it's better now, but I noticed two more things: 
- I couldn't find a way to enter an IP address for the server. This would be required since we also want the client to run on other devices than the designated refbox device.
- The buttons in the top-right corner and the buttons for order confirmation are of different styles. It would be nice if there was one button style across the board.

**Comment by snoato** [comment]
Hey Ivo, thanks again for all your changes! There's one last thing I'd like you to add before I approve. I'll write a new issue for that.

**Comment by userin4o** [comment]
Thanks Dani! With the latest commits this issue as well as no confirmation box on orders with quantity greater than 2 should be fixed. I also made the font size smaller so now the orders should fit inside their container  on laptops screen.

**Review by snoato — APPROVED** [review]
Thanks for your work!

**Pull request merged**
