### PR TITLE
Implementation of team Magenta and Manually giving Points 

### LINKED ISSUE #23: Menu for team name
Currently, you have to type the team-name, would be nice to select the teams from a dropdown menu

### PR DESCRIPTION
**Pull request by userin4o**
This PR fixes #23 and includes:
- fully functional implementation for simulation with team Magenta 
  - Score, Points, Machines are displayed symmetrically
  - Delivered Orders from team Magenta open a confirmation pop-up and are checked if confirmed
  - Shorkey F5 to type Magenta Team Name 
  - Team Menu Dropdown for Magenta
-  Adding Points Manually: A plus button near Score, which triggers an input . Format:  `<Points>, <Reasons>`

### CODE REVIEW

**Comment by snoato** [comment]
Looks good, thank you! I'd approve from my side but I want to know from @TarikViehmann and @morxa what they think about the input method for the points first.

**Review by morxa — COMMENTED** [review]
There is no drop-down menu for Magenta to select the team.

Apart from that, this looks good!

**Comment by userin4o** [comment]
I had forgotten to push the changes.. It should be working now.

**Review by morxa — APPROVED** [review]
Looks good to me!

**Pull request merged**
