### PR TITLE
Add keyboard shortcuts support from old UI

### LINKED ISSUE #6: Continue supporting keyboard shortcuts from old ncurses UI
I'd say this is less important, but it would still be a good idea to keep the hotkeys compatible with the old UI. The refbox computer sometimes has to be used in a confined space, and being the RefBox referee can be a very challenging job. In particular, the RefBox referee should have to spend as little time as possible looking at/interacting with the RefBox GUI. A hotkey can be found and pressed blindly, while clicking with a mouse requires much more attention to the screen. Also people might bump into each other, bump against the mouse, or there might be a crappy laptop with a misconfigured touchpad, etc...

### PR DESCRIPTION
**Pull request by userin4o**
This PR fixes #6. It adds:

- F1 to randomize field
- F2 to Pause/Unpause
- F3 to display Phase menu
- F4 to add Cyan team name
- Update of Vulnerable npm dependencies

### CODE REVIEW

**Comment by morxa** [comment]
Can you please resolve the conflict? It's probably easiest to rebase onto master, drop your changes to package.json, re-add the package, and then continue the rebase, but there may be other ways!

**Comment by userin4o** [comment]
Thnaks for the tip! I think that should have done it?

**Comment by morxa** [comment]
Yes, looks good!

**Comment by morxa** [comment]
Thanks for adding those! Can you also extend this so you can actually do all operations using the keyboard only? Specifically:
* When pressing F1, pressing Enter should confirm ("Yes"), pressing Escape should cancel ("No")
* When pressing F3, can we allow navigation with arrow keys? And then also confirm/cancel with Enter/Escape?

**Comment by userin4o** [comment]
The F1 shorkey now works as desired. As for the F3, I managed to make it close on Esc, but coldn't make it navigable with the arrows. Instead it is navigable with Tab for next and Shift+Tab for previous phase. Enter to confirm works as well.

**Review by morxa — APPROVED** [review]
Nice work!

**Comment by userin4o** [comment]
Thanks for the feedback!

**Pull request merged**
