### PR TITLE
Fixing visual and functional issues given the feedback

### LINKED ISSUE #18: Align robot names to the left
Maybe considering switching positions of Robot names and IP adresses as well

### LINKED ISSUE #19: More static view (non-dynamic dev sizes )
Currently, the size of most Devs or widgets changes depending on the data that is displayed at the moment. 
This visual effect could be seen as a different piece of window changes dynamically.

Would be useful to have all defining lines of the display fixed regardless of the size of the items they hold, giving a more static display

Instances of that issue
- The top gamestatus bare changes depending on the length of the words "PRODUCTION"/ "SETUP"
- The Points widget 
- The Order widget

### LINKED ISSUE #20: Improve highlighting of upcoming orders
For orders that are yet to be scheduled, have either the picture of the order or the text next to it highlighted such that one can distinguish them from orders that are already past its delivery window

### LINKED ISSUE #21: Give option to scroll in refbox log
If necessary, lock the updating of the log via a button. Make it such that you can actually scroll up the log without it jumping to the newest entry all the time.

### LINKED ISSUE #22: Required # of bases display
Its a bit confusing the way the ring color info and filled rings is currently displayed as information that does not belong together are closer to each other,  than irrelevant once.

That is 
#  # COLOR1 - # COLOR2 - # #

It is had to see what the numbers (?#) mean.

suggestion:
Display the required bases for a ring color within the color itself/ above it. or use "/" to separate the info
COL#OR1 - COL#OLR2 - #

### LINKED ISSUE #24: "Complextiy: C#" move above the order "including the length entire order"
For a single order:

Would be more visually appealing to remove the static state information of the order from the middle of the information that we actually need to check Like (requirements and delivery window )

-I would separate the start and end times further apart.(the size of a tab or 4 spaces would be enough).

Currently :

|IMAGELINE1|   O O
IMAGELINE2|    O O
|IMAGELINE3|  complixity: C1
|IMAGELINE3| 12:32 - 17:00

Suggested:

    Complexity: C1
|IMAGE1|
IMAGE2|   O O
|IMAGE3|  O O
|IMAGE3| 12:32   -  17:00

### LINKED ISSUE #25: Swap bots/points list
Currently, the points list pushes down the the list of the bots as it expands. That's unnecessary movement. The bost list has a fixed height, so it should be on top.

### LINKED ISSUE #27: Attention message should not push down log frame
Currently, attention messages open an additional frame above the log frame, pushing it down and leading to layout glitches. One way to avoid that would be to overlay a box *onto* the log frame. It could cover either the top bit or the right half of it.

Generally, I'd say that there should be a fixed set of "top-level" boxes that only change size if the window size changes. Then if you spawn new boxes, these should always be within already existing boxes. That way you should be able to avoid those reflowing glitches altogether.

### LINKED ISSUE #28: Use team color in log messages
The readability of the log messages could be improved significantly (especially when you're looking for something) if team-specific strings were colored accordingly. So we could e.g. color everything that starts with "`C-*`" in cyan and "`M-*`" in magenta.

### LINKED ISSUE #29: every non-textual button should have a tooltip
E.g. the play/pause buttons should say "start game" and "pause game", and the next/previous phase buttons should also say that.

### LINKED ISSUE #30: Change behavior when connecting to localhost fails/when connection is lost
If connection to the localhost fails when you're loading the website, it would be nice to be directed to the IP input field directly instead of having two pop-ups (basically on the assumption: if there is no local server, I must be running on a different device).

Additionally it would be nice to have some permanent red marking on top that indicates the missing connection instead of the pop-ups (this was discussed in a feedback session).

### LINKED ISSUE #31: Spacing of phase switch buttons should be constant
The buttons that are used to switch the phases should have equal spacing between them no matter what the name of the phase is. This is more user friendly as the mouse doesn't need to be moved (e.g. when switching from setup to exploration using the errors you would have to move your mouse to switch to production).

### LINKED ISSUE #33: Getting weird Connection Lost popup when switching to correct address
When i type some invalid port into the websocket port field (e.g. `localhost:1233`) and press enter, then i correctly get some "Connection has been lost" messages, typing the correct port aftwerwards (`localhost:1234`) correctly establishes the refbox connecton but again there appears a "_Connection has been lost_" popup. Also happens when you simply are connected and type the correct address again.

### PR DESCRIPTION
**Pull request by userin4o**
This PR fixes #18, fixes #19, fixes #20, fixes #21, fixes #22, fixes #24, fixes #25, fixes #27, fixes #28, fixes #29, fixes #30, fixes #31, fixes #33

 Main highlight: attention messages have separate container on the right side of the log, so they dont push the log.

### CODE REVIEW

**Comment by snoato** [comment]
Thank you Ivo, the improvements look good! There are still some minor issues though: 
- regarding issue #19 I think it would be great to fit it all on a normal laptop screen (you can probably decrease the font size)
- there is a minor alignment issue with the IP addresses of the robots
- regarding issue #25 it should be sufficient to just swap robot list and point list (as you did), but to keep the points at the very top because they are kind of the key information
- somehow the order-confirmation pop-ups didn't work anymore when I tested it

**Comment by userin4o** [comment]
Dani, thanks for the feedback, it was really on point! 
Could you have another look after the latest commits?

**Comment by snoato** [comment]
Thank you for changes Ivo! It looks really good. After discussing with Tarik there is only one thing left: you are using "cmplx" to mark the complexity of an order, we would prefer "complexity" if the space allows it or "complex". Besides that, great work!

**Comment by userin4o** [comment]
Glad you both like it! Using Complexity takes somewhat unnecessary space, so I went with Complex instead.
Thank you both!

**Review by snoato — COMMENTED** [review]
Looks great! Thanks for working through the Issues! :rocket:

**Review by snoato — APPROVED** [review]

**Comment by userin4o** [comment]
Thank you for all the feedback!

**Pull request merged**
